### ISSUE TITLE
Benchmark "input size" needs to be scaled to their clarity size

### ISSUE THREAD

**Issue by kantai** [blockstack/clarity-benchmarking#18]
Clarity cost functions typically sum the input argument's object size to feed an input to the cost function. For example, in https://github.com/blockstack/stacks-blockchain/blob/master/src/vm/functions/sequences.rs#L45

```rust
    let mut arg_size = 0;
    for a in args.iter() {
        arg_size = arg_size.cost_overflow_add(a.size().into())?;
    }

    runtime_cost(ClarityCostFunction::ListCons, env, arg_size)?;
```

However, the input size in the benchmarks refers to different values (e.g., an input size of 10 may mean 10 integers). When digesting the benchmark results, the analysis scripts should scale _x_ dimension appropriately.

**Comment by gregorycoppola** [comment]
Do we really need to do this? I think that the slope of the line is already telling you the empirical speed

**Comment by kantai** [comment]
Yes, we do.

**Comment by gregorycoppola** [comment]
Oh whoops. Didn't mean to close it!

**Comment by gregorycoppola** [comment]
What is the "clarity size"? Is that the number of bytes in the Clarity object? @kantai 

Is there somewhere that lists the clarity sizes of bytes?

**Comment by kantai** [comment]
Yes -- the Clarity size is the number of bytes that the type system calculates for a Clarity object. The implementation of this size is `Value::size` in `src/vm/types/`, and it's specified in https://github.com/stacksgov/sips/blob/main/sips/sip-006/sip-006-runtime-cost-assessment.md#type-signature-size

**Comment by gregorycoppola** [comment]
So, are you thinking here that there will be "one adjustment per benchmark"? Each determined logically from the code?

**Comment by kantai** [comment]
> So, are you thinking here that there will be "one adjustment per benchmark"? Each determined logically from the code?

Yep -- it'll need to look at the implementation (i.e., the code that assesses the runtime cost) and the benchmark code for each benchmark.

**Comment by reedrosenbluth** [comment]
Isn't the solution here to make sure all of the clarity generators in the benchmarking suite are using the same units for input size as the code that invokes the cost function? If that was the case, would there still be a need to do this scaling?

**Comment by kantai** [comment]
It may be possible to supply an input scale by configuration in criterion, but I'm not sure of it.

If we wanted the generated inputs to be the same units as the cost functions, I think that's only possible in specific cases. That would work for the list cons example above -- the input array could be constructed as a list of bools, because those have size `1`, so a list of 16 of them would really be evaluated as `16` during runtime cost assessment. But it wouldn't work for things like `fetch-var`, where the argument size would be like `(4 + 16)` because it is counting the overhead of the list as well.
